# Generated by Django 3.2.6 on 2021-11-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_redemedpointsummary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifiedPointList',
            new_name='AggregatePointList',
        ),
    ]
